# Generated by Django 4.1 on 2022-10-06 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_khach_hang', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_khach_hang', models.CharField(max_length=40)),
                ('khach_hang_thuong_xuyen', models.IntegerField()),
                ('ma_nguoi_dung', models.ForeignKey(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.PROTECT, to='nguoi_dung.nguoidung')),
            ],
            options={
                'db_table': 'khach_hang',
                'managed': True,
            },
        ),
    ]
