# Generated by Django 4.1 on 2022-11-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khach_hang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='duong',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='phuong',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='quan',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='so_nha',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='thanh_pho',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
