# Generated by Django 4.1 on 2022-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khach_hang', '0002_khachhang_duong_khachhang_phuong_khachhang_quan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='sdt',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
