# Generated by Django 4.1 on 2022-10-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('san_pham', '0001_initial'),
        ('khach_hang', '0001_initial'),
        ('khuyen_mai', '0002_alter_khuyenmai_options'),
        ('shipper', '0002_alter_shipper_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('ma_don_hang', models.IntegerField(primary_key=True, serialize=False)),
                ('ngay_dat', models.DateTimeField()),
                ('ngay_giao', models.DateTimeField()),
                ('so_nha', models.CharField(max_length=30)),
                ('duong', models.CharField(max_length=30)),
                ('phuong', models.CharField(max_length=30)),
                ('quan', models.CharField(max_length=30)),
                ('thanh_pho', models.CharField(max_length=30)),
                ('tong_tien_hang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ap_dung_khuyen_mai', models.IntegerField()),
                ('gia_tri_khuyen_mai', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tong_so_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma_khach_hang', models.ForeignKey(db_column='ma_khach_hang', on_delete=django.db.models.deletion.PROTECT, to='khach_hang.khachhang')),
                ('ma_khuyen_mai', models.ForeignKey(db_column='ma_khuyen_mai', on_delete=django.db.models.deletion.PROTECT, to='khuyen_mai.khuyenmai')),
                ('ma_san_pham', models.ForeignKey(db_column='ma_san_pham', on_delete=django.db.models.deletion.PROTECT, to='san_pham.sanpham')),
                ('ma_shipper', models.ForeignKey(db_column='ma_shipper', on_delete=django.db.models.deletion.PROTECT, to='shipper.shipper')),
            ],
            options={
                'db_table': 'don_hang',
                'managed': True,
            },
        ),
    ]
