# Generated by Django 4.1 on 2022-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='trang_thai',
            field=models.IntegerField(default=0),
        ),
    ]
