# Generated by Django 4.1 on 2022-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0002_donhang_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ngay_dat',
            field=models.DateTimeField(blank=True),
        ),
    ]
