# Generated by Django 4.1 on 2022-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0004_alter_donhang_ngay_giao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ma_don_hang',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
