# Generated by Django 4.1 on 2022-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0005_alter_donhang_ma_don_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ngay_dat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
