# Generated by Django 4.1 on 2022-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0006_alter_donhang_ngay_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ngay_giao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
