# Generated by Django 4.1 on 2022-11-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0007_alter_donhang_ngay_giao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='tong_so_tien',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='tong_tien_hang',
        ),
    ]
