# Generated by Django 4.1 on 2022-11-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0008_remove_donhang_tong_so_tien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='duong',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='phuong',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='quan',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='so_nha',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='thanh_pho',
        ),
    ]
