# Generated by Django 4.1 on 2022-11-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0009_remove_donhang_duong_remove_donhang_phuong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='ap_dung_khuyen_mai',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='gia_tri_khuyen_mai',
        ),
    ]
