# Generated by Django 4.1 on 2022-11-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khach_hang', '0002_khachhang_duong_khachhang_phuong_khachhang_quan_and_more'),
        ('san_pham', '0007_alter_sanpham_ten_san_pham'),
        ('don_hang', '0010_remove_donhang_ap_dung_khuyen_mai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slsapham', models.IntegerField()),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khach_hang.khachhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_pham.sanpham')),
            ],
        ),
    ]
