# Generated by Django 4.1 on 2022-11-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='donhang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='don_hang.donhang'),
        ),
    ]
