# Generated by Django 4.1 on 2022-11-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khuyen_mai', '0002_alter_khuyenmai_options'),
        ('shipper', '0002_alter_shipper_options'),
        ('san_pham', '0007_alter_sanpham_ten_san_pham'),
        ('don_hang', '0012_cart_donhang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ma_khuyen_mai',
            field=models.ForeignKey(db_column='ma_khuyen_mai', null=True, on_delete=django.db.models.deletion.PROTECT, to='khuyen_mai.khuyenmai'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ma_san_pham',
            field=models.ForeignKey(db_column='ma_san_pham', null=True, on_delete=django.db.models.deletion.PROTECT, to='san_pham.sanpham'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ma_shipper',
            field=models.ForeignKey(db_column='ma_shipper', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipper.shipper'),
        ),
    ]
