# Generated by Django 4.1 on 2022-11-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0013_alter_donhang_ma_khuyen_mai_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
