# Generated by Django 4.1 on 2022-11-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_hang', '0014_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='tong_tien_hang',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
