# Generated by Django 4.1 on 2022-10-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_khuyen_mai', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_khuyen_mai', models.CharField(max_length=30)),
                ('mo_ta_khuyen_mai', models.CharField(max_length=100)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('khuyen_mai_bang_tien', models.IntegerField()),
                ('gia_tri_khuyen_mai', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'khuyen_mai',
                'managed': False,
            },
        ),
    ]
