# Generated by Django 4.1 on 2022-10-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('san_pham', '0001_initial'),
        ('don_hang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('ma_san_pham', models.OneToOneField(db_column='ma_san_pham', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='san_pham.sanpham')),
                ('so_luong', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ma_don_hang', models.ForeignKey(db_column='ma_don_hang', on_delete=django.db.models.deletion.PROTECT, to='don_hang.donhang')),
            ],
            options={
                'db_table': 'chi_tiet_don_hang',
                'managed': True,
                'unique_together': {('ma_san_pham', 'ma_don_hang')},
            },
        ),
    ]
