# Generated by Django 4.1 on 2022-11-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chi_tiet_don_hang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='tong_tien_hang',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
