# Generated by Django 4.1 on 2022-11-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chi_tiet_don_hang', '0002_chitietdonhang_tong_tien_hang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietdonhang',
            name='tong_tien_hang',
        ),
    ]
