# Generated by Django 4.1 on 2022-10-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('don_hang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanh_toan_tien_mat', models.IntegerField()),
                ('ma_thanh_toan', models.CharField(max_length=30)),
                ('ma_don_hang', models.ForeignKey(db_column='ma_don_hang', on_delete=django.db.models.deletion.PROTECT, to='don_hang.donhang')),
            ],
            options={
                'db_table': 'thanh_toan',
                'managed': True,
            },
        ),
    ]
