# Generated by Django 4.1 on 2022-10-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('ma_nguoi_dung', models.IntegerField(primary_key=True, serialize=False)),
                ('tai_khoan', models.CharField(max_length=30)),
                ('mat_khau', models.CharField(max_length=30)),
                ('loai_tai_khoan', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nguoi_dung',
                'managed': False,
            },
        ),
    ]
