# Generated by Django 4.1 on 2022-10-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'managed': True},
        ),
    ]
