# Generated by Django 4.1 on 2022-10-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loai_san_pham', '0002_alter_loaisanpham_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaisanpham',
            name='ma_loai',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
