# Generated by Django 4.1 on 2022-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loai_san_pham', '0003_alter_loaisanpham_ma_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaisanpham',
            name='hinh_anh_loai',
            field=models.ImageField(blank=True, null=True, upload_to='img/sanpham/'),
        ),
    ]
