# Generated by Django 4.1 on 2022-10-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loai_san_pham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_san_pham', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=30)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('don_vi_tinh', models.CharField(max_length=10)),
                ('ma_loai', models.ForeignKey(db_column='ma_loai', on_delete=django.db.models.deletion.PROTECT, to='loai_san_pham.loaisanpham')),
            ],
            options={
                'db_table': 'san_pham',
                'managed': True,
            },
        ),
    ]
