# Generated by Django 4.1 on 2022-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='mo_ta',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='thanh_phan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ma_san_pham',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
