# Generated by Django 4.1 on 2022-10-25 01:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0003_alter_sanpham_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/img/sanpham/'), upload_to=''),
        ),
    ]
