# Generated by Django 4.1 on 2022-10-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0005_alter_sanpham_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='img/sanpham/'),
        ),
    ]
