# Generated by Django 4.1 on 2022-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0006_alter_sanpham_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='ten_san_pham',
            field=models.CharField(max_length=100),
        ),
    ]
