# Generated by Django 4.1 on 2022-10-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('ma_shipper', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_shipper', models.CharField(max_length=30)),
                ('tien_luong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nam_sinh', models.DateField()),
            ],
            options={
                'db_table': 'shipper',
                'managed': False,
            },
        ),
    ]
